### ISSUE TITLE
Planner service failed with real robot

### ISSUE THREAD

**Issue by ajay1606** [unr-arl/gbplanner_ros#49]
Hello,

With your continuous support, we were able to test this planner with `bag_file` and everything working as expected.

But, when i tried to test module with real robot (SPOT robot), getting error in like below. 

![image](https://github.com/ntnu-arl/gbplanner_ros/assets/29722843/c77adac2-41f4-4310-80fd-aca1786acf45)

```
[ INFO] [1711142413.262462715]: getLocalPointcloud time: 0.019490
[ERROR] [1711142413.262526028]: Exception thrown while processing service call: bool pcl::PCA<PointT>::initCompute() [with PointT = pcl::PointXYZI] in /usr/include/pcl-1.10/pcl/common/impl/pca.hpp @ 58 : [pcl::PCA::initCompute] number of points < 3
[ERROR] [1711142413.262815389]: Service call failed: service [/gbplanner] responded with an error: bool pcl::PCA<PointT>::initCompute() [with PointT = pcl::PointXYZI] in /usr/include/pcl-1.10/pcl/common/impl/pca.hpp @ 58 : [pcl::PCA::initCompute] number of points < 3
[ERROR] [1711142413.262846490]: Planner service failed
```

Also, In rviz error with marker visulization as below:

![Screenshot from 2024-03-22 16-16-02](https://github.com/ntnu-arl/gbplanner_ros/assets/29722843/d7cb4c8b-0581-477a-9b6e-f648d1408331)

Any suggestions please !

**Comment by MihirDharmadhikari** [comment]
Hi @ajay1606 ,

It seems that the voxblox map is not generated. The error seems to arise as there aren't enough points in the point cloud used to generate the adaptive local bounding box. 
Can you check that the correct point cloud topic is passed to the gbplanner node, and there exists a tf between the frame in which the point cloud is published and the fixed frame? Also, the fixed frame used by gbplanner is `world`, check if you have the same in your SLAM. Otherwise, you can put a static transform between the two.

Best,
Mihir

**Comment by ajay1606** [comment]
@MihirDharmadhikari Thank you so much for your quick response. You are right there is problem with input LiDAR data. I just forgot to comment the param `/use_sim_time:true`, after setting it to false, able to see the data.

Though after getting data, still path planning not working. It just stop at this stage showing no feasible path found. But if i run in bag file, path planning working fine.

![Screenshot from 2024-03-23 13-37-14](https://github.com/ntnu-arl/gbplanner_ros/assets/29722843/78a1d42c-7756-43f8-ae90-a71f6c3743b8)

For robot control I am using same `pure_persuit` one that shared in your repository and i have modified the algorithm input by topic instead of action. Hence i have written call back inside `pure_persuit` to receive `pci_command_path` and compute `cmd_velocity` and `carrot_point`. 

Currently planning_configuration file set with the following parameters:

```
run_mode: kReal
trigger_mode: kManual
robot_type: kGround
output_type: kTopic
init_motion_enable: false
planner_trigger_lead_time: 0.0
smooth_heading_enable: true
init_motion:
  z_takeoff: 2.5
  z_drop: 1.7
  x_forward: 3.0

# Group related parameters to be shared between nodes.
RobotDynamics:
  v_max: 0.3
  v_init_max: 0.3
  v_homing_max: 0.3
  yaw_rate_max: 0.5
  dt: 0.05

```
After moving robot little, able to see the trajectory like below:
![Screenshot from 2024-03-23 15-41-01](https://github.com/ntnu-arl/gbplanner_ros/assets/29722843/e0171787-3043-4262-a7f5-c462eebf2ffc)

But the current point estimation is very much small to make robot make movement. So robot continuous to be remain in the same location. Would you please help to fix this issue !

Currently relying `/carrot_point ` pose to control the robot (SPOT) using `/spot/go_to_pose `


Thanks in advance.
